### ISSUE TITLE
Error: spawn EACCES

### ISSUE THREAD

**Issue by oaktower** [dvajs/dva-cli#115]
在macOS v10.12.6上执行dva new 的时候报错如下: 

/usr/local/lib/node_modules/dva-cli/bin/dva-new
internal/child_process.js:325
    throw errnoException(err, 'spawn');
    ^

Error: spawn EACCES
    at _errnoException (util.js:1041:11)
    at ChildProcess.spawn (internal/child_process.js:325:11)
    at exports.spawn (child_process.js:493:9)
    at spawn (/usr/local/lib/node_modules/dva-cli/node_modules/win-spawn/index.js:54:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/dva-cli/bin/dva:33:10)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)

执行chmod -R 755 /usr/local/lib/node_modules/dva-cli后恢复正常

**Comment by sorrycc** [comment]
应该是 npm@5.x 的问题，试试 cnpm 。
