### ISSUE TITLE
下载最新版本的dva-cli 0.8.2, 尝试 dva -g route product-list 有问题

### ISSUE THREAD

**Issue by zhangming0305** [dvajs/dva-cli#125]
下载最新版本的dva-cli 0.8.2, 尝试 dva -g route product-list 有问题
```
/usr/local/lib/node_modules/dva-cli/bin/dva-generate
      create  routeComponent src/routes/ProductList.js, src/routes/ProductList.css
      create  route product-list with src/routes/ProductList.js
AssertionError: getRouterTree: component should be one of Router, Route, Redirect, IndexRedirect, IndexRoute
    at parse (/usr/local/lib/node_modules/dva-cli/node_modules/dva-ast/lib/collections/Router.js:57:28)
    at ret.children.node.children.filter.map.node (/usr/local/lib/node_modules/dva-cli/node_modules/dva-ast/lib/collections/Router.js:94:93)
    at Array.map (native)
    at parse (/usr/local/lib/node_modules/dva-cli/node_modules/dva-ast/lib/collections/Router.js:94:81)
    at NodePath.simpleMap.path (/usr/local/lib/node_modules/dva-cli/node_modules/dva-ast/lib/collections/Router.js:117:13)
    at NodePath.<anonymous> (/usr/local/lib/node_modules/dva-cli/node_modules/dva-ast/lib/collections/Helper.js:21:28)
    at __paths.forEach (/usr/local/lib/node_modules/dva-cli/node_modules/jscodeshift/src/Collection.js:76:36)
    at Array.forEach (native)
    at Collection.forEach (/usr/local/lib/node_modules/dva-cli/node_modules/jscodeshift/src/Collection.js:75:18)
    at Collection.simpleMap (/usr/local/lib/node_modules/dva-cli/node_modules/dva-ast/lib/collections/Helper.js:20:10)

```
```
node -v 
v6.9.1
npm -v 
3.10.8
dva -v
dva-cli:  #0.8.2
```

**Comment by fordguo** [comment]
+1

**Comment by tongjinle** [comment]
+1
看了下源码，好像是switch不认识

**Comment by Elvenisboy** [comment]
+1, node8也不行

**Comment by prc333** [comment]
把route.js里新创建的Router放到Switch里就好了

**Comment by aozhiwei** [comment]
这个bug是每次必现的，这么久了都不修复吗，导致无法使用哎

**Comment by myhui** [comment]
+1

**Comment by aprilfall** [comment]
这玩意儿能用？？？

**Comment by miaozilong** [comment]
这个bug估计不会修复了  现在这功能都删了！
