### ISSUE TITLE
dva g route test报错

### ISSUE THREAD

**Issue by joriewong** [dvajs/dva-cli#138]
dva版本
```
dva-cli: 0.8.2
```
dva g route test 可以生成文件，但是会报如下错误     
```
C:\Users\baver\AppData\Roaming\npm\node_modules\dva-cli\bin\dva-generate
      create  routeComponent src/routes/Test.js, src/routes/Test.css
      create  route test with src/routes/Test.js
SyntaxError: Unexpected token (8:21)
    at Parser.pp.raise (C:\Users\baver\AppData\Roaming\npm\node_modules\dva-cli\node_modules\_babylon@5.8.38@babylon\lib\parser\location.js:24:13)
    at Parser.pp.unexpected (C:\Users\baver\AppData\Roaming\npm\node_modules\dva-cli\node_modules\_babylon@5.8.38@babylon\lib\parser\util.js:82:8)
    at Parser.pp.parseExprAtom (C:\Users\baver\AppData\Roaming\npm\node_modules\dva-cli\node_modules\_babylon@5.8.38@babylon\lib\parser\expression.js:425:12)
    at Parser.parseExprAtom (C:\Users\baver\AppData\Roaming\npm\node_modules\dva-cli\node_modules\_babylon@5.8.38@babylon\lib\plugins\jsx\index.js:412:22)
    at Parser.pp.parseExprSubscripts (C:\Users\baver\AppData\Roaming\npm\node_modules\dva-cli\node_modules\_babylon@5.8.38@babylon\lib\parser\expression.js:236:19)
    at Parser.pp.parseMaybeUnary (C:\Users\baver\AppData\Roaming\npm\node_modules\dva-cli\node_modules\_babylon@5.8.38@babylon\lib\parser\expression.js:217:19)
    at Parser.pp.parseExprOps (C:\Users\baver\AppData\Roaming\npm\node_modules\dva-cli\node_modules\_babylon@5.8.38@babylon\lib\parser\expression.js:163:19)
    at Parser.pp.parseMaybeConditional (C:\Users\baver\AppData\Roaming\npm\node_modules\dva-cli\node_modules\_babylon@5.8.38@babylon\lib\parser\expression.js:145:19)
    at Parser.pp.parseMaybeAssign (C:\Users\baver\AppData\Roaming\npm\node_modules\dva-cli\node_modules\_babylon@5.8.38@babylon\lib\parser\expression.js:112:19)
    at Parser.pp.parseFunctionBody (C:\Users\baver\AppData\Roaming\npm\node_modules\dva-cli\node_modules\_babylon@5.8.38@babylon\lib\parser\expression.js:738:22)

```

**Comment by sorrycc** [comment]
时间原因，dva g 功能先暂停了。
