### ISSUE TITLE
Spread operator syntax error

### ISSUE THREAD

**Issue by haobingwang** [dvajs/dva-cli#25]
dva g model Hello
```
/Users/Bing/.nvm/versions/node/v4.4.7/lib/node_modules/dva-cli/bin/dva-generate
/Users/Bing/.nvm/versions/node/v4.4.7/lib/node_modules/dva-cli/node_modules/dva-ast/lib/combine.js:47
    data: [...oldModels.data, ...newModels.data],
           ^^^

SyntaxError: Unexpected token ...
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/Bing/.nvm/versions/node/v4.4.7/lib/node_modules/dva-cli/node_modules/dva-ast/index.js:6:19)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
```

 dva -v

```
0.6.0
```

**Comment by sorrycc** [comment]
node 用 0.6.x 试试?
