### ISSUE TITLE
dva init初始化报错，这是什么原因啊

### ISSUE THREAD

**Issue by RichardFei** [dvajs/dva-cli#5]
npm\node_modules\.dva-cli_npminstall\node_modu
les\.0.4.3@dva-cli\bin\dva-init                                                
events.js:141                                                                  
      throw er; // Unhandled 'error' event                                     
      ^                                                                                                  
                                                                               
Error: spawn cmd ENOENT                                                        
    at exports._errnoException (util.js:870:11)                                
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)  
    at onErrorNT (internal/child_process.js:344:16)                            
    at nextTickCallbackWith2Args (node.js:442:9)                               
    at process._tickCallback (node.js:356:17)                                  
    at Function.Module.runMain (module.js:443:11)                              
    at startup (node.js:139:18)                                                
    at node.js:968:3

**Comment by sorrycc** [comment]
应该是这里报错了，https://github.com/dvajs/dva-cli/blob/master/src/install.js#L5，你可以试着排查下原因。

**Comment by RichardFei** [comment]
感觉不像是install，这里有个问题，我如果在c:/windows/system32下面 
执行dva init 会报

我在dva-init 
![image](https://cloud.githubusercontent.com/assets/15813110/18627252/99927728-7e8c-11e6-9f5b-f6bf22592f0a.png)

这个时候会执行到这里然后跳出，
但是如果新建一个文件夹下面，就只会报这个错误，这样的话我就没法排查了
![image](https://cloud.githubusercontent.com/assets/15813110/18627284/c37ef5f2-7e8c-11e6-857c-28205289746e.png)

**Comment by RichardFei** [comment]
不好意思，日了狗了，我查了原因和脚本无关，我的配置出问题了，这个错误的原因是我没有把c:/windows/system32配置到 path 下面，悲催的人
