### ISSUE TITLE
dva g route 多级目录会报错

### ISSUE THREAD

**Issue by czjxy881** [dvajs/dva-cli#67]
+ 执行 `dva g route tables/grand/authority`
+ 报错
```shell
/usr/local/lib/node_modules/dva-cli/bin/dva-generate
      create  routeComponent src/routes/Tables/grand/authority.js, src/routes/Tables/grand/authority.css
SyntaxError: Unexpected token (5:15)
    at Parser.pp.raise (/usr/local/lib/node_modules/dva-cli/node_modules/babel-core/node_modules/babylon/lib/parser/location.js:24:13)
    at Parser.pp.unexpected (/usr/local/lib/node_modules/dva-cli/node_modules/babel-core/node_modules/babylon/lib/parser/util.js:82:8)
    at Parser.pp.expect (/usr/local/lib/node_modules/dva-cli/node_modules/babel-core/node_modules/babylon/lib/parser/util.js:76:33)
    at Parser.pp.parseFunctionParams (/usr/local/lib/node_modules/dva-cli/node_modules/babel-core/node_modules/babylon/lib/parser/statement.js:529:8)
    at Parser.parseFunctionParams (/usr/local/lib/node_modules/dva-cli/node_modules/babel-core/node_modules/babylon/lib/plugins/flow.js:936:13)
    at Parser.pp.parseFunction (/usr/local/lib/node_modules/dva-cli/node_modules/babel-core/node_modules/babylon/lib/parser/statement.js:523:8)
    at Parser.pp.parseFunctionStatement (/usr/local/lib/node_modules/dva-cli/node_modules/babel-core/node_modules/babylon/lib/parser/statement.js:262:15)
    at Parser.pp.parseStatement (/usr/local/lib/node_modules/dva-cli/node_modules/babel-core/node_modules/babylon/lib/parser/statement.js:79:19)
    at Parser.parseStatement (/usr/local/lib/node_modules/dva-cli/node_modules/babel-core/node_modules/babylon/lib/plugins/flow.js:655:22)
    at Parser.pp.parseTopLevel (/usr/local/lib/node_modules/dva-cli/node_modules/babel-core/node_modules/babylon/lib/parser/statement.js:30:21)

```
+ 此时生成出来了router下的文件，但是文件内容并不正确，router.js也没有修改成功。

**Comment by sorrycc** [comment]
目前不支持。

**Comment by DoubleK2013** [comment]
这个需求挺普遍的，希望能进入支持的计划，感谢
