### ISSUE TITLE
antd dva框架创建新项目报错

### ISSUE THREAD

**Issue by wanghongxun226** [dvajs/dva-cli#81]
1.环境
node.js v6.10.2 dva v0.7.8
2.错误信息
D:\html\dora>dva new app
C:\Program Files\nodejs\node_modules\dva-cli\bin\dva-new
events.js:160
throw er; // Unhandled 'error' event
^

Error: spawn cmd ENOENT
at exports._errnoException (util.js:1018:11)
at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
at onErrorNT (internal/child_process.js:367:16)
at _combinedTickCallback (internal/process/next_tick.js:80:11)
at process._tickCallback (internal/process/next_tick.js:104:9)
at Module.runMain (module.js:606:11)
at run (bootstrap_node.js:393:7)
at startup (bootstrap_node.js:150:9)
at bootstrap_node.js:508:3

3.错误重现步骤，参照官网给的链接https://ant.design/docs/react/practical-projects-cn
4.dva命令除了dva -v 能够输出0.7.8，其他命令都是报错的，包括new init等

**Comment by YMFL** [comment]
一样的问题

**Comment by kolf** [comment]
一样的问题

**Comment by netbeen** [comment]
我也遇到一样的问题，node@8.4.0 dva-cli@0.8.1

**Comment by sorrycc** [comment]
应该是 npm@5.x 的问题，试试 cnpm 。

**Comment by bsqql123** [comment]
@sorrycc 能不能详细一点，使用cnpm 还是无法解决，你的npm@5.x 无法点开

**Comment by FanRenFei** [comment]
我也是，一样的问题，求详细解答
