### ISSUE TITLE
什么情况？重新安装了都不行

### ISSUE THREAD

**Issue by GreenAppleOne** [dvajs/dva-cli#94]
/usr/local/lib/node_modules/dva-cli/bin/dva-generate
      create  routeComponent src/routes/Sds.js, src/routes/Sds.css
TypeError: root.findRouters(...).getRouterInfo is not a function
    at transform (/usr/local/lib/node_modules/dva-cli/node_modules/_dva-ast@0.3.4@dva-ast/lib/transform.js:42:32)
    at exports.default (/usr/local/lib/node_modules/dva-cli/node_modules/_dva-ast@0.3.4@dva-ast/lib/api/index.js:46:36)
    at /usr/local/lib/node_modules/dva-cli/lib/generate.js:92:27
    at generate (/usr/local/lib/node_modules/dva-cli/lib/generate.js:108:11)
    at Object.<anonymous> (/usr/local/lib/node_modules/dva-cli/bin/dva-generate:11:27)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)

**Comment by lelewan** [comment]
我也遇到这个问题，有办法解决吗？
